version: '2'
services:
  web:
    hostname: barrier-ui
    container_name: barrier-ui
    build: client
    ports:
      - 4200:4200

  express:
    hostname: api
    container_name: express-api
    build: server
    ports:
        - "3000:3000"
    links:
        - db
    depends_on:
      - db

  db:
    hostname: database:database
    container_name: mariadb-database
    build: ./database/barrier
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: not_secure
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: barrier